version: "3.8"
services:
  reminder-api:
    build:
      context: .
      dockerfile: ./worker #Change to prod for prod
    ports:
      - "80:8000"
    volumes:
      - ./src:/usr/src/app
      #- logvolume01:/var/log
    networks:
      - db-net
  mongo:
    image: mongo:latest
    networks:
      - db-net
networks:
  db-net: {}


