version: "3.8"
services:
  reminder-api:
    build:
      context: .
      dockerfile: ./worker #Change to prod for prod

    volumes:
      - ./src:/usr/src/app
    networks:
      - web
      - db-net
    expose:
      - "8000"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:api.gurule.rocks"
      - "traefik.basic.port=8000"
      - "traefik.basic.protocol=http"
    restart: always
  mongo:
    image: mongo:latest
    networks:
      - db-net
    restart: always
networks:
  db-net: {}
  web:
    external: true


